server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 路由到搜索微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/** #授权中心微服务
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true #携带本身的header头信息
  sensitive-headers: #
leyou:
  jwt:
    pubKeyPath: F:\\Study\\leyou\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth #"-"表示集合
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item