server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.56.6
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 15秒不发送就过期
mybatis:
  type-aliases-package: com.leyou.item.pojo

